sudo: required
services: 
  - docker

before_install:
  - docker build -t vlamoly/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true vlamoly/react-test npm test 

after_success: 
  - docker build -t vlamoly/multi-client ./client
  - docker build -t vlamoly/multi-nginx ./nginx
  - docker build -t vlamoly/multi-server ./server
  - docker build -t vlamoly/multi-worker ./worker
# Login to docker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push images to docker hub
  - docker push vlamoly/multi-client
  - docker push vlamoly/multi-nginx 
  - docker push vlamoly/multi-server
  - docker push vlamoly/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-088649115377'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY